### PR TITLE
feat(recordings): update start/stop a recording guide for 2.2.0

### LINKED ISSUE #82: [Task] Update "start a recording" section
Beyond updating screenshots, the updated version should also describe the "archive on stop" option.

### PR DESCRIPTION
**Pull request by maxcao13**
Fixes #82 

Also, seems like this repo doesn't use the GitHub action to automatically close issues with the Fixes, Closes keywords, so there's some issues, I assume, left unclosed.

### CODE REVIEW

**Comment by andrewazores** [comment]
I don't think that keyword processing is done by an Action actually, I think it should just be done automatically by the GitHub API... I'll have to take a closer look at it.

**Comment by maxcao13** [comment]
Oh, weird then. I just notice that this https://github.com/cryostatio/cryostatio.github.io/pull/75 should've probably closed this https://github.com/cryostatio/cryostatio.github.io/issues/65, but it didn't. :/

**Comment by andrewazores** [comment]
Oh, I think that's because the PR was merged into a branch other than `main`, actually.

**Review by andrewazores — APPROVED** [review]

**Comment by andrewazores** [comment]
We'll see if merging `version-220` into `main` automatically cascades and closes all those issues, I guess.

**Pull request merged**
