### PR TITLE
feat(version): copy guides to 2.3.0 version and update latest to 2.4.0

### LINKED ISSUE #140: [Epic] 2.4.0 release
See https://github.com/cryostatio/cryostatio.github.io/issues/102

- [ ] #141
- [x] #142
- [x] #143
- [x] #144
- [ ] #90 
- [ ] #97

### PR DESCRIPTION
**Pull request by andrewazores**
- chore(version): copy current content to 2.3.0 versioned guide, update latest version to 2.4.0
- chore(versions): update operator-sdk version
- feat(versions): add recommended cert-manager version
- feat(demo): use latest release branch for surge URL dynamically

Related to cryostatio/cryostat#1695
Fixes #140 

Roll-up of other 2.4.0 release changes, including:
- [x] #147 
- [x] #148 
- [x] #157

### CODE REVIEW

**Review by mwangggg — APPROVED** [review]
looks good to me

**Comment by aali309** [comment]
I think using smart triggers needs to be formatted (terms and phrases)

**Comment by andrewazores** [comment]
Could you add that formatting @aali309 ?

**Comment by aali309** [comment]
> Could you add that formatting @aali309 ?

Yes, I'm doing it at the moment.

**Pull request merged**
