### PR TITLE
chore(gem): update dependencies

### LINKED ISSUE #122: [Task] Update Gemfile dependencies

### PR DESCRIPTION
**Pull request by andrewazores**
Fixes #122

Tested and seems to work on Fedora 38, which has ruby `3.2.2`. I could not get the previous dependencies to build and run properly after upgrading Fedora versions. Hopefully this upgrade does not break things for anyone still on Fedora 37, or any other distro that ships an older ruby.

### CODE REVIEW

**Review by maxcao13 — APPROVED** [review]
Was able to sucessfully bundle and run on Fedora 36 with ruby version `3.1.4p223`.

**Comment by tthvo** [comment]
I am still on Fedora 35 and seeing this after bundle install

```
$ bundle install
Fetching gem metadata from https://rubygems.org/...........
Your bundle is locked to sass-embedded (1.62.1-x86_64-linux) from rubygems repository https://rubygems.org/ or installed locally, but that
version can no longer be found in that source. That means the author of sass-embedded (1.62.1-x86_64-linux) has removed it. You'll need to
update your bundle to a version other than sass-embedded (1.62.1-x86_64-linux) that hasn't been removed in order to install.

```

**Comment by tthvo** [comment]
> You two should both upgrade :-)

:)) right been delaying that for long.

**Comment by tthvo** [comment]
Tho, do we need to specify Fedora version in README tho?

**Comment by andrewazores** [comment]
We could, though it isn't necessarily Fedora-specific. I think we should just maintain it for the two currently supported Fedora versions.

**Comment by tthvo** [comment]
Sounds good!

**Review by tthvo — APPROVED** [review]

**Pull request merged**
