### PR TITLE
feat(config): add config for local development

### LINKED ISSUE #61: [Task] Add config and README steps for local development
Currently, local development semi-requires the developer to edit `_config.yml` and change the `url` property to point to `localhost`, or else images will load from the static GitHub Pages website rather than from the local dev server. The `bundle exec` invocation also does not watch for changes or automatically reload on changes, which it can do and should be recommended for the developer to do for convenience.

### PR DESCRIPTION
**Pull request by andrewazores**
- feat(config): add -dev config overrides
- docs(readme): use hot reload, change watch, and dev override config

Fixes #61

### CODE REVIEW

**Review by tthvo — DISMISSED** [review]
Looks great to me! This is so much more convenient!

**Comment by tthvo** [comment]
I wonder if we should have a section in README for `prereq` and a section for `run locally`.

Like this line should come in `prereq` and before `bundle install`...?
https://github.com/cryostatio/cryostatio.github.io/blob/596afb4ebe1191128203a9824ba2ff5af0a18d4b/README.md?plain=1#L12

**Review by maxcao13 — APPROVED** [review]
Looks good to me as well.

**Review by tthvo — DISMISSED** [review]

**Review by tthvo — COMMENTED** [review]
Should we add a requirement for compilers as specified here?

https://jekyllrb.com/docs/installation/

I think we did run into issues with missing compilers to install `event-machine`, sassc` and other native extensions?

**Comment by andrewazores** [comment]
@tthvo ah, I don't think I've run into that before. So in the package list under `Prerequisites`, you're saying I should add `ruby`, `ruby-devel`, `rubygems`, `gcc`, `gcc-c++`, and `make`? And a link to that Jekyll document for good measure.

**Comment by tthvo** [comment]
> @tthvo ah, I don't think I've run into that before. So in the package list under `Prerequisites`, you're saying I should add `ruby`, `ruby-devel`, `rubygems`, `gcc`, `gcc-c++`, and `make`? And a link to that Jekyll document for good measure.

Right! I think that would be great!

Do you think `ruby` and `rubygems` is already included in `ruby-devel`?

**Comment by andrewazores** [comment]
```bash
$ dnf repoquery --requires rubygems
Last metadata expiration check: 0:00:21 ago on Mon 04 Jul 2022 04:18:55 PM.
/usr/bin/ruby
ruby(release)
rubygem(psych) >= 3.3.0
rubygem(psych) >= 3.3.2
$ dnf repoquery --requires ruby-devel
Last metadata expiration check: 0:00:28 ago on Mon 04 Jul 2022 04:18:55 PM.
/usr/bin/pkg-config
libruby.so.3.0
libruby.so.3.0()(64bit)
ruby(x86-32) = 3.0.2-151.fc35
ruby(x86-32) = 3.0.4-153.fc35
ruby(x86-64) = 3.0.2-151.fc35
ruby(x86-64) = 3.0.4-153.fc35
rubygems
$ dnf repoquery --requires ruby
Last metadata expiration check: 0:00:33 ago on Mon 04 Jul 2022 04:18:55 PM.
/usr/bin/ruby
glibc >= 2.33.9000-43.fc35
libc.so.6(GLIBC_2.34)
libc.so.6(GLIBC_2.34)(64bit)
libcrypt.so.2
libcrypt.so.2()(64bit)
libgmp.so.10
libgmp.so.10()(64bit)
libm.so.6
libm.so.6()(64bit)
libruby.so.3.0
libruby.so.3.0()(64bit)
libz.so.1
libz.so.1()(64bit)
rtld(GNU_HASH)
ruby-libs(x86-32) = 3.0.2-151.fc35
ruby-libs(x86-32) = 3.0.4-153.fc35
ruby-libs(x86-64) = 3.0.2-151.fc35
ruby-libs(x86-64) = 3.0.4-153.fc35
```

So on Fedora, installing `ruby-devel` would pull in `ruby` and `rubygems`, but that might not be true for all distros. It may not even always be true for Fedora - it's true now for the way that the Ruby maintainer(s) have split up the packages, but it could change. Best bet is to list those dependencies all separately and let the developer or their package manager sort it out.

**Comment by tthvo** [comment]
> ```shell
> rubygems
> ```

Ahh that makes sense now! Including explicit dependencies would best then!

**Review by tthvo — APPROVED** [review]

**Pull request merged**
