### PR TITLE
docs(get-started): Authenticate with OpenShift username/password

### PR DESCRIPTION
**Pull request by jan-law**
Fixes https://github.com/cryostatio/cryostat/issues/791
Rebased on top of #37 

> I'm thinking it would make sense to put the new Token Authentication section in a "2.1.0 Getting Started" post and leaving the "2.0.0 Getting Started" page as is. We could include the version drop down already used by the Guides page.

I've preserved the original Get Started doc in the `/versions` folder.

The Get Started page was also missing a `title` field. What do you think about renaming the getting started page title from "Cryostat 2.1.0" to "Get Started"? This would also update the browser tab title just like the Guides page does.

### CODE REVIEW

**Comment by andrewazores** [comment]
> The Get Started page was also missing a title field. What do you think about renaming the getting started page title from "Cryostat 2.1.0" to "Get Started"? This would also update the browser tab title just like the Guides page does.

Sounds like a good idea

**Review by andrewazores — COMMENTED** [review]
New content looks good, will merge closer to 2.1.0 release

**Comment by jan-law** [comment]
Your PR in #49 includes the change I wanted to make with this PR, including the SSO screenshot. I'm okay with closing this PR and keeping the changes on #49. What do you think?

**Comment by andrewazores** [comment]
Oh, sorry, I had forgotten this PR was already opened. I guess we can keep #49 since I updated a few other screenshots there too.

**Comment by jan-law** [comment]
No worries, sounds good

**Pull request closed without merging**
